version: '3.8'

services:

  django:

    container_name: django-container
    build: 
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/santa_app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=09340903409340934
      - ALLOWED_HOSTS=localhost,127.0.0.1

